// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecretSantaServer.Data;

#nullable disable

namespace SecretSantaServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216152616_auth")]
    partial class auth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecretSantaServer.Models.Assignment", b =>
                {
                    b.Property<int>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int?>("SantaId")
                        .HasColumnType("integer")
                        .HasColumnName("santa_id");

                    b.HasKey("RecipientId")
                        .HasName("pk_assignments");

                    b.HasIndex("SantaId")
                        .HasDatabaseName("ix_assignments_santa_id");

                    b.HasIndex("GameId", "SantaId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_game_id_santa_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("SecretSantaServer.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasIndex("AdminId")
                        .IsUnique()
                        .HasDatabaseName("ix_games_admin_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_games_code");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("SecretSantaServer.Models.GameMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Letter")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("letter");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_game_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_game_members_user_id");

                    b.HasIndex("GameId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_game_members_game_id_user_id");

                    b.ToTable("game_members", (string)null);
                });

            modelBuilder.Entity("SecretSantaServer.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SecretSantaServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SecretSantaServer.Models.UserCredentials", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GithubId")
                        .HasColumnType("text")
                        .HasColumnName("github_id");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("UserId")
                        .HasName("pk_user_auth_data");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_data_email");

                    b.HasIndex("GithubId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_data_github_id");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_data_google_id");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_data_telegram_id");

                    b.ToTable("user_auth_data", (string)null);
                });

            modelBuilder.Entity("SecretSantaServer.Models.Assignment", b =>
                {
                    b.HasOne("SecretSantaServer.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_games_game_id");

                    b.HasOne("SecretSantaServer.Models.GameMember", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_game_members_recipient_id");

                    b.HasOne("SecretSantaServer.Models.GameMember", "Santa")
                        .WithMany()
                        .HasForeignKey("SantaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assignments_game_members_santa_id");

                    b.Navigation("Game");

                    b.Navigation("Recipient");

                    b.Navigation("Santa");
                });

            modelBuilder.Entity("SecretSantaServer.Models.Game", b =>
                {
                    b.HasOne("SecretSantaServer.Models.User", "Admin")
                        .WithOne()
                        .HasForeignKey("SecretSantaServer.Models.Game", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_games_users_admin_id");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("SecretSantaServer.Models.GameMember", b =>
                {
                    b.HasOne("SecretSantaServer.Models.Game", "Game")
                        .WithMany("GameMembers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_members_games_game_id");

                    b.HasOne("SecretSantaServer.Models.User", "User")
                        .WithMany("GameMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_members_users_user_id");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecretSantaServer.Models.UserCredentials", b =>
                {
                    b.HasOne("SecretSantaServer.Models.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("SecretSantaServer.Models.UserCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_auth_data_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecretSantaServer.Models.Game", b =>
                {
                    b.Navigation("GameMembers");
                });

            modelBuilder.Entity("SecretSantaServer.Models.User", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("GameMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
